# Generated by Django 4.1.1 on 2022-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myaoo', '0004_client_profile_image_alter_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
